<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.475">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>report</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="report_files/libs/clipboard/clipboard.min.js"></script>
<script src="report_files/libs/quarto-html/quarto.js"></script>
<script src="report_files/libs/quarto-html/popper.min.js"></script>
<script src="report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="report_files/libs/quarto-html/anchor.min.js"></script>
<link href="report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="report_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="report_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">



<section id="kaduna" class="level1">
<h1>Kaduna</h1>
<p>The state’s population was 8.3M as of the last census in 2019(ref_population_census), with an estimated population of 9.8M in 2022.</p>
<p>The state experiences two distinct seasons: the dry season (December - February) and the rainy season (March - November), with annual rainfall averaging around 1,175.0 millimeters.</p>
<p>The state contributed an estimated 5.6% of Nigeria’s 65M malaria cases in 2021. Between 2018 and 2021, estimated cases increased from 3.3M to 3.9M, and the estimated incidence increased from 340.6 to 381.7 per 1000 population(ref_wmr). Malaria prevalence by microscopy decreased from 36.7% in 2015 to 16.2% in 2021(ref_dhs_mis).</p>
<p>The state conducted its most recent round of Insecticide Treated Nets (ITN) mass campaign in 2019. Since 2013, over 9.1M ITN have been distributed through mass distribution. The proportion of those who slept under ITNs the night before the surveys of decreased from 61.6% in 2015 to 57.1% in 2021. Care seeking among children with fever in the state increased from 58.9% in 2015 to 83.8% in 2021. Children with fever who had blood taken from a finger or heel for testing increased from 16.4% in 2015 to 18.4% in 2021. The coverage of intermittent preventive treatment of malaria in pregnancy who received two or more doses of SP decreased from 17.3% in 2015 to 16.4% in 2021.(ref_dhs_mis)</p>
<p>Cumulative estimated malaria cases averted was 1.3M in 2015 decreased to -292.2K in 2021.</p>
<p>An estimated 1.3M cases were averted between 2009 and 2015, no cases were estimated to be cumulatively averted between 2015 and 2021 as an increase in cases was observed during this period</p>
<table class="table">
<colgroup>
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"># Kwara</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"># Sokoto</td>
</tr>
<tr class="even">
<td style="text-align: left;">The state’s population was 5.9M as of the last census in 2019(ref_population_census), with an estimated population of 5.9M in 2022.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The state experiences two distinct seasons: the dry season (November - April) and the rainy season (May - October), with annual rainfall averaging around 586.4 millimeters.</td>
</tr>
<tr class="even">
<td style="text-align: left;">The state contributed an estimated 3.1% of Nigeria’s 65M malaria cases in 2021. Between 2018 and 2021, estimated cases decreased from 2.6M to 2.2M, and the estimated incidence decreased from 408.4 to 308.2 per 1000 population(ref_wmr). Malaria prevalence by microscopy decreased from 46.6% in 2015 to 35.9% in 2021(ref_dhs_mis).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The state conducted its most recent round of Insecticide Treated Nets (ITN) mass campaign in 2017. Since 2013, over 2.5M ITN have been distributed through mass distribution. The proportion of those who slept under ITNs the night before the surveys of decreased from 48.7% in 2015 to 31.1% in 2021. Care seeking among children with fever in the state increased from 26.1% in 2015 to 71.1% in 2021. Children with fever who had blood taken from a finger or heel for testing increased from 4.9% in 2015 to 22.0% in 2021. The coverage of intermittent preventive treatment of malaria in pregnancy who received two or more doses of SP decreased from 25.9% in 2015 to 17.0% in 2021.(ref_dhs_mis)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cumulative estimated malaria cases averted was -4.4M in 2015 decreased to -6.7M in 2021.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">No cases were estimated to be cumulatively averted between 2009 and 2015 as an increase in cases was observed during this period, no cases were estimated to be cumulatively averted between 2015 and 2021 as an increase in cases was observed during this period</td>
</tr>
</tbody>
</table>
</section>
<section id="akwa-ibom" class="level1">
<h1>Akwa Ibom</h1>
<p>The state’s population was 4.8M as of the last census in 2019(ref_population_census), with an estimated population of 6.7M in 2022.</p>
<p>The state experiences two distinct seasons: the dry season (November - March) and the rainy season (April - October), with annual rainfall averaging around 2,432.1 millimeters.</p>
<p>The state contributed an estimated 1.1% of Nigeria’s 65M malaria cases in 2021. Between 2018 and 2021, estimated cases increased from 747.4K to 758.2K, and the estimated incidence increased from 268.9 to 300.3 per 1000 population(ref_wmr). Malaria prevalence by microscopy increased from 22.8% in 2015 to 30.1% in 2021(ref_dhs_mis).</p>
<p>The state conducted its most recent round of Insecticide Treated Nets (ITN) mass campaign in 2018. Since 2013, over 2.6M ITN have been distributed through mass distribution. The proportion of those who slept under ITNs the night before the surveys of decreased from 36.8% in 2015 to 17.8% in 2021. Care seeking among children with fever in the state decreased from 70.5% in 2015 to 44.4% in 2021. Children with fever who had blood taken from a finger or heel for testing decreased from 10.9% in 2015 to 4.9% in 2021. The coverage of intermittent preventive treatment of malaria in pregnancy who received two or more doses of SP decreased from 23.6% in 2015 to 22.1% in 2021.(ref_dhs_mis)</p>
<p>Cumulative estimated malaria cases averted was 3.3M in 2015 increased to 4.1M in 2021.</p>
<p>An estimated 3.3M cases were averted between 2009 and 2015, and4.1M between 2009 and 2021</p>
<table class="table">
<colgroup>
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"># Ebonyi</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"># Ekiti</td>
</tr>
<tr class="even">
<td style="text-align: left;">The state’s population was 3.4M as of the last census in 2019(ref_population_census), with an estimated population of 3.9M in 2022.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The state experiences two distinct seasons: the dry season (November - March) and the rainy season (April - October), with annual rainfall averaging around 1,333.5 millimeters.</td>
</tr>
<tr class="even">
<td style="text-align: left;">The state contributed an estimated 0.8% of Nigeria’s 65M malaria cases in 2021. Between 2018 and 2021, estimated cases decreased from 606.5K to 562.9K, and the estimated incidence decreased from 324.7 to 324.4 per 1000 population(ref_wmr). Malaria prevalence by microscopy decreased from 28.8% in 2015 to 20.8% in 2021(ref_dhs_mis).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The state conducted its most recent round of Insecticide Treated Nets (ITN) mass campaign in 2014. The proportion of those who slept under ITNs the night before the surveys of decreased from 27.3% in 2015 to 9.9% in 2021. Care seeking among children with fever in the state was 41.2% in 2021. Children with fever who had blood taken from a finger or heel for testing was 6.0% in 2021. The coverage of intermittent preventive treatment of malaria in pregnancy who received two or more doses of SP increased from 5.0% in 2015 to 9.3% in 2021.(ref_dhs_mis)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cumulative estimated malaria cases averted was 755.9K in 2015 decreased to -62.1K in 2021.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">An estimated 755.9K cases were averted between 2009 and 2015, no cases were estimated to be cumulatively averted between 2015 and 2021 as an increase in cases was observed during this period</td>
</tr>
</tbody>
</table>
</section>
<section id="kano" class="level1">
<h1>Kano</h1>
<p>The state’s population was 14.3M as of the last census in 2019(ref_population_census), with an estimated population of 15.8M in 2022.</p>
<p>The state experiences two distinct seasons: the dry season (November - April) and the rainy season (May - October), with annual rainfall averaging around 813.5 millimeters.</p>
<p>The state contributed an estimated 9.5% of Nigeria’s 65M malaria cases in 2021. Between 2018 and 2021, estimated cases increased from 6.4M to 6.7M, and the estimated incidence decreased from 412.9 to 397.9 per 1000 population(ref_wmr). Malaria prevalence by microscopy decreased from 27.7% in 2015 to 25.5% in 2021(ref_dhs_mis).</p>
<p>The state conducted its most recent round of Insecticide Treated Nets (ITN) mass campaign in 2019. Since 2013, over 14.6M ITN have been distributed through mass distribution. The proportion of those who slept under ITNs the night before the surveys of increased from 43.8% in 2015 to 63.0% in 2021. Care seeking among children with fever in the state decreased from 86.9% in 2015 to 44.5% in 2021. Children with fever who had blood taken from a finger or heel for testing increased from 5.0% in 2015 to 13.6% in 2021. The coverage of intermittent preventive treatment of malaria in pregnancy who received two or more doses of SP increased from 16.0% in 2015 to 24.9% in 2021.(ref_dhs_mis)</p>
<p>Cumulative estimated malaria cases averted was 4.0K in 2015 decreased to -6.5M in 2021.</p>
<p>An estimated 4.0K cases were averted between 2009 and 2015, no cases were estimated to be cumulatively averted between 2015 and 2021 as an increase in cases was observed during this period</p>
<table class="table">
<colgroup>
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"># Katsina</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"># Delta</td>
</tr>
<tr class="even">
<td style="text-align: left;">The state’s population was 5.3M as of the last census in 2019(ref_population_census), with an estimated population of 6.8M in 2022.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The state experiences two distinct seasons: the dry season (December - February) and the rainy season (March - November), with annual rainfall averaging around 2,088.8 millimeters.</td>
</tr>
<tr class="even">
<td style="text-align: left;">The state contributed an estimated 1.5% of Nigeria’s 65M malaria cases in 2021. Between 2018 and 2021, estimated cases increased from 1.1M to 1.1M, and the estimated incidence increased from 238.4 to 242.3 per 1000 population(ref_wmr). Malaria prevalence by microscopy decreased from 20.4% in 2015 to 10.0% in 2021(ref_dhs_mis).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The state conducted its most recent round of Insecticide Treated Nets (ITN) mass campaign in 2019. Since 2013, over 3.2M ITN have been distributed through mass distribution. The proportion of those who slept under ITNs the night before the surveys of increased from 18.1% in 2015 to 26.2% in 2021. Care seeking among children with fever in the state decreased from 65.7% in 2015 to 42.6% in 2021. Children with fever who had blood taken from a finger or heel for testing increased from 8.1% in 2015 to 20.9% in 2021. The coverage of intermittent preventive treatment of malaria in pregnancy who received two or more doses of SP decreased from 6.8% in 2015 to 4.2% in 2021.(ref_dhs_mis)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cumulative estimated malaria cases averted was 293.0K in 2015 decreased to -2.3M in 2021.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">An estimated 293.0K cases were averted between 2009 and 2015, no cases were estimated to be cumulatively averted between 2015 and 2021 as an increase in cases was observed during this period</td>
</tr>
</tbody>
</table>
</section>
<section id="enugu" class="level1">
<h1>Enugu</h1>
<p>The state’s population was 4.4M as of the last census in 2019(ref_population_census), with an estimated population of 5.2M in 2022.</p>
<p>The state experiences two distinct seasons: the dry season (January - January) and the rainy season (February - December), with annual rainfall averaging around 1,548.2 millimeters.</p>
<p>The state contributed an estimated 1.7% of Nigeria’s 65M malaria cases in 2021. Between 2018 and 2021, estimated cases increased from 1.0M to 1.2M, and the estimated incidence increased from 214.9 to 231.2 per 1000 population(ref_wmr). Malaria prevalence by microscopy increased from 10.5% in 2015 to 24.3% in 2021(ref_dhs_mis).</p>
<p>The state conducted its most recent round of Insecticide Treated Nets (ITN) mass campaign in 2011. The proportion of those who slept under ITNs the night before the surveys of decreased from 14.1% in 2015 to 9.8% in 2021. Care seeking among children with fever in the state decreased from 88.4% in 2015 to 73.2% in 2021. Children with fever who had blood taken from a finger or heel for testing decreased from 13.5% in 2015 to 12.1% in 2021. The coverage of intermittent preventive treatment of malaria in pregnancy who received two or more doses of SP increased from 9.5% in 2015 to 10.2% in 2021.(ref_dhs_mis)</p>
<p>Cumulative estimated malaria cases averted was 1.6M in 2015 increased to 2.3M in 2021.</p>
<p>An estimated 1.6M cases were averted between 2009 and 2015, and2.3M between 2009 and 2021</p>
<table class="table">
<colgroup>
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"># Edo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"># Oyo</td>
</tr>
<tr class="even">
<td style="text-align: left;">The state’s population was 7.5M as of the last census in 2019(ref_population_census), with an estimated population of 9.5M in 2022.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The state experiences two distinct seasons: the dry season (November - March) and the rainy season (April - October), with annual rainfall averaging around 1,088.0 millimeters.</td>
</tr>
<tr class="even">
<td style="text-align: left;">The state contributed an estimated 2.6% of Nigeria’s 65M malaria cases in 2021. Between 2018 and 2021, estimated cases increased from 1.8M to 1.9M, and the estimated incidence increased from 294.2 to 311.4 per 1000 population(ref_wmr). Malaria prevalence by microscopy increased from 19.2% in 2015 to 20.9% in 2021(ref_dhs_mis).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The state conducted its most recent round of Insecticide Treated Nets (ITN) mass campaign in 2021. Since 2013, over 8.9M ITN have been distributed through mass distribution. The proportion of those who slept under ITNs the night before the surveys of decreased from 31.4% in 2015 to 31.2% in 2021. Care seeking among children with fever in the state decreased from 83.3% in 2015 to 46.0% in 2021. Children with fever who had blood taken from a finger or heel for testing decreased from 58.7% in 2015 to 34.5% in 2021. The coverage of intermittent preventive treatment of malaria in pregnancy who received two or more doses of SP increased from 14.1% in 2015 to 15.7% in 2021.(ref_dhs_mis)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cumulative estimated malaria cases averted was 2.3M in 2015 increased to 3.1M in 2021.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">An estimated 2.3M cases were averted between 2009 and 2015, and3.1M between 2009 and 2021</td>
</tr>
</tbody>
</table>
</section>
<section id="gombe" class="level1">
<h1>Gombe</h1>
<p>The state’s population was 3.6M as of the last census in 2019(ref_population_census), with an estimated population of 3.9M in 2022.</p>
<p>The state experiences two distinct seasons: the dry season (November - April) and the rainy season (May - October), with annual rainfall averaging around 851.0 millimeters.</p>
<p>The state contributed an estimated 1.7% of Nigeria’s 65M malaria cases in 2021. Between 2018 and 2021, estimated cases increased from 1.1M to 1.2M, and the estimated incidence increased from 353.9 to 359.3 per 1000 population(ref_wmr). Malaria prevalence by microscopy decreased from 28.6% in 2015 to 17.7% in 2021(ref_dhs_mis).</p>
<p>The state conducted its most recent round of Insecticide Treated Nets (ITN) mass campaign in 2021. Since 2013, over 6.0M ITN have been distributed through mass distribution. The proportion of those who slept under ITNs the night before the surveys of increased from 33.6% in 2015 to 63.3% in 2021. Care seeking among children with fever in the state decreased from 85.4% in 2015 to 56.4% in 2021. Children with fever who had blood taken from a finger or heel for testing increased from 3.8% in 2015 to 17.4% in 2021. The coverage of intermittent preventive treatment of malaria in pregnancy who received two or more doses of SP increased from 12.1% in 2015 to 25.3% in 2021.(ref_dhs_mis)</p>
<p>Cumulative estimated malaria cases averted was 544.1K in 2015 decreased to -166.4K in 2021.</p>
<p>An estimated 544.1K cases were averted between 2009 and 2015, no cases were estimated to be cumulatively averted between 2015 and 2021 as an increase in cases was observed during this period</p>
<table class="table">
<colgroup>
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"># Rivers</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"># Cross River</td>
</tr>
<tr class="even">
<td style="text-align: left;">The state’s population was 4.2M as of the last census in 2019(ref_population_census), with an estimated population of 4.6M in 2022.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The state experiences two distinct seasons: the dry season (November - April) and the rainy season (May - October), with annual rainfall averaging around 2,284.6 millimeters.</td>
</tr>
<tr class="even">
<td style="text-align: left;">The state contributed an estimated 1.0% of Nigeria’s 65M malaria cases in 2021. Between 2018 and 2021, estimated cases increased from 716.3K to 725.8K, and the estimated incidence increased from 271.2 to 288.8 per 1000 population(ref_wmr). Malaria prevalence by microscopy decreased from 26.1% in 2015 to 23.6% in 2021(ref_dhs_mis).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The state conducted its most recent round of Insecticide Treated Nets (ITN) mass campaign in 2019. The proportion of those who slept under ITNs the night before the surveys of decreased from 49.6% in 2015 to 30.6% in 2021. Care seeking among children with fever in the state decreased from 61.8% in 2015 to 58.4% in 2021. Children with fever who had blood taken from a finger or heel for testing increased from 10.8% in 2015 to 14.8% in 2021. The coverage of intermittent preventive treatment of malaria in pregnancy who received two or more doses of SP increased from 23.2% in 2015 to 27.3% in 2021.(ref_dhs_mis)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cumulative estimated malaria cases averted was 1.3M in 2015 increased to 2.5M in 2021.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">An estimated 1.3M cases were averted between 2009 and 2015, and2.5M between 2009 and 2021</td>
</tr>
</tbody>
</table>
</section>
<section id="ondo" class="level1">
<h1>Ondo</h1>
<p>The state’s population was 5.0M as of the last census in 2019(ref_population_census), with an estimated population of 5.6M in 2022.</p>
<p>The state experiences two distinct seasons: the dry season (November - April) and the rainy season (May - October), with annual rainfall averaging around 1,574.2 millimeters.</p>
<p>The state contributed an estimated 1.6% of Nigeria’s 65M malaria cases in 2021. Between 2018 and 2021, estimated cases decreased from 1.2M to 1.1M, and the estimated incidence decreased from 325.9 to 304.0 per 1000 population(ref_wmr). Malaria prevalence by microscopy increased from 21.3% in 2015 to 26.7% in 2021(ref_dhs_mis).</p>
<p>The state conducted its most recent round of Insecticide Treated Nets (ITN) mass campaign in 2021. Since 2013, over 4.3M ITN have been distributed through mass distribution. The proportion of those who slept under ITNs the night before the surveys of decreased from 20.1% in 2015 to 17.7% in 2021. Care seeking among children with fever in the state decreased from 59.2% in 2015 to 48.8% in 2021. Children with fever who had blood taken from a finger or heel for testing decreased from 28.3% in 2015 to 7.8% in 2021. The coverage of intermittent preventive treatment of malaria in pregnancy who received two or more doses of SP increased from 16.6% in 2015 to 18.2% in 2021.(ref_dhs_mis)</p>
<p>Cumulative estimated malaria cases averted was 512.5K in 2015 decreased to 213.3K in 2021.</p>
<p>An estimated 512.5K cases were averted between 2009 and 2015, and213.3K between 2009 and 2021</p>
<table class="table">
<colgroup>
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"># Abia</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"># Bayelsa</td>
</tr>
<tr class="even">
<td style="text-align: left;">The state’s population was 2.4M as of the last census in 2019(ref_population_census), with an estimated population of 2.7M in 2022.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The state experiences two distinct seasons: the dry season (December - April) and the rainy season (May - November), with annual rainfall averaging around 2,701.6 millimeters.</td>
</tr>
<tr class="even">
<td style="text-align: left;">The state contributed an estimated 0.3% of Nigeria’s 65M malaria cases in 2021. Between 2018 and 2021, estimated cases decreased from 230.4K to 206.7K, and the estimated incidence increased from 246.5 to 257.1 per 1000 population(ref_wmr). Malaria prevalence by microscopy decreased from 31.4% in 2015 to 16.7% in 2021(ref_dhs_mis).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The state conducted its most recent round of Insecticide Treated Nets (ITN) mass campaign in 2011. The proportion of those who slept under ITNs the night before the surveys of decreased from 18.2% in 2015 to 17.9% in 2021. Care seeking among children with fever in the state decreased from 56.3% in 2015 to 52.2% in 2021. Children with fever who had blood taken from a finger or heel for testing increased from 6.7% in 2015 to 10.4% in 2021. The coverage of intermittent preventive treatment of malaria in pregnancy who received two or more doses of SP increased from 4.3% in 2015 to 11.6% in 2021.(ref_dhs_mis)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cumulative estimated malaria cases averted was -558.1K in 2015 decreased to -1.6M in 2021.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">No cases were estimated to be cumulatively averted between 2009 and 2015 as an increase in cases was observed during this period, no cases were estimated to be cumulatively averted between 2015 and 2021 as an increase in cases was observed during this period</td>
</tr>
</tbody>
</table>
</section>
<section id="lagos" class="level1">
<h1>Lagos</h1>
<p>The state’s population was 12.8M as of the last census in 2019(ref_population_census), with an estimated population of 15.1M in 2022.</p>
<p>The state experiences two distinct seasons: the dry season (November - February) and the rainy season (March - October), with annual rainfall averaging around 1,535.8 millimeters.</p>
<p>The state contributed an estimated 1.5% of Nigeria’s 65M malaria cases in 2021. Between 2018 and 2021, estimated cases decreased from 1.1M to 1.0M, and the estimated incidence increased from 164.5 to 174.9 per 1000 population(ref_wmr). Malaria prevalence by microscopy was 2.6% in 2021(ref_dhs_mis).</p>
<p>The state conducted its most recent round of Insecticide Treated Nets (ITN) mass campaign in 2011. The proportion of those who slept under ITNs the night before the surveys of decreased from 11.1% in 2015 to 9.6% in 2021. Care seeking among children with fever in the state increased from 67.8% in 2015 to 73.4% in 2021. Children with fever who had blood taken from a finger or heel for testing increased from 10.0% in 2015 to 26.7% in 2021. The coverage of intermittent preventive treatment of malaria in pregnancy who received two or more doses of SP decreased from 11.7% in 2015 to 6.6% in 2021.(ref_dhs_mis)</p>
<p>Cumulative estimated malaria cases averted was 3.0M in 2015 decreased to -1.6M in 2021.</p>
<p>An estimated 3.0M cases were averted between 2009 and 2015, no cases were estimated to be cumulatively averted between 2015 and 2021 as an increase in cases was observed during this period</p>
<table class="table">
<colgroup>
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"># Bauchi</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"># Kebbi</td>
</tr>
<tr class="even">
<td style="text-align: left;">The state’s population was 5.0M as of the last census in 2019(ref_population_census), with an estimated population of 5.3M in 2022.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The state experiences two distinct seasons: the dry season (November - March) and the rainy season (April - October), with annual rainfall averaging around 845.9 millimeters.</td>
</tr>
<tr class="even">
<td style="text-align: left;">The state contributed an estimated 2.8% of Nigeria’s 65M malaria cases in 2021. Between 2018 and 2021, estimated cases decreased from 2.6M to 2.0M, and the estimated incidence decreased from 556.3 to 402.9 per 1000 population(ref_wmr). Malaria prevalence by microscopy decreased from 63.6% in 2015 to 49.0% in 2021(ref_dhs_mis).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The state conducted its most recent round of Insecticide Treated Nets (ITN) mass campaign in 2018. Since 2013, over 2.2M ITN have been distributed through mass distribution. The proportion of those who slept under ITNs the night before the surveys of increased from 37.6% in 2015 to 38.2% in 2021. Care seeking among children with fever in the state increased from 44.3% in 2015 to 47.1% in 2021. Children with fever who had blood taken from a finger or heel for testing increased from 8.6% in 2015 to 20.2% in 2021. The coverage of intermittent preventive treatment of malaria in pregnancy who received two or more doses of SP decreased from 18.2% in 2015 to 16.1% in 2021.(ref_dhs_mis)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cumulative estimated malaria cases averted was -1.7M in 2015 decreased to -4.0M in 2021.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">No cases were estimated to be cumulatively averted between 2009 and 2015 as an increase in cases was observed during this period, no cases were estimated to be cumulatively averted between 2015 and 2021 as an increase in cases was observed during this period</td>
</tr>
</tbody>
</table>
</section>
<section id="plateau" class="level1">
<h1>Plateau</h1>
<p>The state’s population was 4.4M as of the last census in 2019(ref_population_census), with an estimated population of 4.9M in 2022.</p>
<p>The state experiences two distinct seasons: the dry season (September - April) and the rainy season (May - August), with annual rainfall averaging around 1,042.7 millimeters.</p>
<p>The state contributed an estimated 5.5% of Nigeria’s 65M malaria cases in 2021. Between 2018 and 2021, estimated cases increased from 2.8M to 3.9M, and the estimated incidence increased from 257.3 to 286.5 per 1000 population(ref_wmr). Malaria prevalence by microscopy decreased from 35.8% in 2015 to 18.8% in 2021(ref_dhs_mis).</p>
<p>The state conducted its most recent round of Insecticide Treated Nets (ITN) mass campaign in 2020. Since 2013, over 4.5M ITN have been distributed through mass distribution. The proportion of those who slept under ITNs the night before the surveys of decreased from 38.4% in 2015 to 26.7% in 2021. Care seeking among children with fever in the state decreased from 78.6% in 2015 to 52.7% in 2021. Children with fever who had blood taken from a finger or heel for testing decreased from 19.6% in 2015 to 10.5% in 2021. The coverage of intermittent preventive treatment of malaria in pregnancy who received two or more doses of SP increased from 15.7% in 2015 to 23.4% in 2021.(ref_dhs_mis)</p>
<p>Cumulative estimated malaria cases averted was 1.2M in 2015 increased to 4.4M in 2021.</p>
<p>An estimated 1.2M cases were averted between 2009 and 2015, and4.4M between 2009 and 2021</p>
<table class="table">
<colgroup>
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"># Nasarawa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"># Ogun</td>
</tr>
<tr class="even">
<td style="text-align: left;">The state’s population was 5.9M as of the last census in 2019(ref_population_census), with an estimated population of 6.3M in 2022.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The state experiences two distinct seasons: the dry season (October - February) and the rainy season (March - September), with annual rainfall averaging around 1,332.3 millimeters.</td>
</tr>
<tr class="even">
<td style="text-align: left;">The state contributed an estimated 5.3% of Nigeria’s 65M malaria cases in 2021. Between 2018 and 2021, estimated cases increased from 3.0M to 3.7M, and the estimated incidence increased from 267.3 to 279.9 per 1000 population(ref_wmr). Malaria prevalence by microscopy increased from 14.7% in 2015 to 24.9% in 2021(ref_dhs_mis).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The state conducted its most recent round of Insecticide Treated Nets (ITN) mass campaign in 2018. Since 2013, over 6.7M ITN have been distributed through mass distribution. The proportion of those who slept under ITNs the night before the surveys of increased from 12.2% in 2015 to 21.7% in 2021. Care seeking among children with fever in the state increased from 36.0% in 2015 to 39.4% in 2021. Children with fever who had blood taken from a finger or heel for testing decreased from 28.0% in 2015 to 24.3% in 2021. The coverage of intermittent preventive treatment of malaria in pregnancy who received two or more doses of SP decreased from 16.3% in 2015 to 9.2% in 2021.(ref_dhs_mis)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cumulative estimated malaria cases averted was 2.1M in 2015 decreased to 1.1M in 2021.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">An estimated 2.1M cases were averted between 2009 and 2015, and1.1M between 2009 and 2021</td>
</tr>
</tbody>
</table>
</section>
<section id="anambra" class="level1">
<h1>Anambra</h1>
<p>The state’s population was 5.6M as of the last census in 2019(ref_population_census), with an estimated population of 6.5M in 2022.</p>
<p>The state experiences two distinct seasons: the dry season (November - February) and the rainy season (March - October), with annual rainfall averaging around 1,667.3 millimeters.</p>
<p>The state contributed an estimated 2.1% of Nigeria’s 65M malaria cases in 2021. Between 2018 and 2021, estimated cases increased from 1.2M to 1.5M, and the estimated incidence increased from 171.4 to 199.7 per 1000 population(ref_wmr). Malaria prevalence by microscopy decreased from 10.2% in 2015 to 5.4% in 2021(ref_dhs_mis).</p>
<p>The state conducted its most recent round of Insecticide Treated Nets (ITN) mass campaign in 2021. Since 2013, over 2.7M ITN have been distributed through mass distribution. The proportion of those who slept under ITNs the night before the surveys of decreased from 24.1% in 2015 to 10.3% in 2021. Care seeking among children with fever in the state increased from 64.7% in 2015 to 88.5% in 2021. Children with fever who had blood taken from a finger or heel for testing decreased from 10.2% in 2015 to 7.7% in 2021. The coverage of intermittent preventive treatment of malaria in pregnancy who received two or more doses of SP increased from 13.5% in 2015 to 18.3% in 2021.(ref_dhs_mis)</p>
<p>Cumulative estimated malaria cases averted was 3.4M in 2015 increased to 6.3M in 2021.</p>
<p>An estimated 3.4M cases were averted between 2009 and 2015, and6.3M between 2009 and 2021</p>
<table class="table">
<colgroup>
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"># Zamfara</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"># Osun</td>
</tr>
<tr class="even">
<td style="text-align: left;">The state’s population was 4.2M as of the last census in 2019(ref_population_census), with an estimated population of 5.7M in 2022.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The state experiences two distinct seasons: the dry season (November - February) and the rainy season (March - October), with annual rainfall averaging around 1,361.8 millimeters.</td>
</tr>
<tr class="even">
<td style="text-align: left;">The state contributed an estimated 2.1% of Nigeria’s 65M malaria cases in 2021. Between 2018 and 2021, estimated cases increased from 1.5M to 1.5M, and the estimated incidence decreased from 327.2 to 326.5 per 1000 population(ref_wmr). Malaria prevalence by microscopy decreased from 33.4% in 2015 to 19.3% in 2021(ref_dhs_mis).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The state conducted its most recent round of Insecticide Treated Nets (ITN) mass campaign in 2020. Since 2013, over 6.6M ITN have been distributed through mass distribution. The proportion of those who slept under ITNs the night before the surveys of increased from 21.4% in 2015 to 35.3% in 2021. Care seeking among children with fever in the state decreased from 70.2% in 2015 to 61.0% in 2021. Children with fever who had blood taken from a finger or heel for testing increased from 8.9% in 2015 to 29.7% in 2021. The coverage of intermittent preventive treatment of malaria in pregnancy who received two or more doses of SP increased from 5.4% in 2015 to 8.5% in 2021.(ref_dhs_mis)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cumulative estimated malaria cases averted was 745.8K in 2015 decreased to 676.7K in 2021.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">An estimated 745.8K cases were averted between 2009 and 2015, and676.7K between 2009 and 2021</td>
</tr>
</tbody>
</table>
</section>
<section id="yobe" class="level1">
<h1>Yobe</h1>
<p>The state’s population was 3.4M as of the last census in 2019(ref_population_census), with an estimated population of 4.0M in 2022.</p>
<p>The state experiences two distinct seasons: the dry season (October/November - April/May) and the rainy season (May/June - September/October), with annual rainfall averaging around 547.2 millimeters.</p>
<p>The state contributed an estimated 1.8% of Nigeria’s 65M malaria cases in 2021. Between 2018 and 2021, estimated cases increased from 1.1M to 1.2M, and the estimated incidence increased from 280.9 to 288.7 per 1000 population(ref_wmr). Malaria prevalence by microscopy increased from 18.9% in 2015 to 20.5% in 2021(ref_dhs_mis).</p>
<p>The state conducted its most recent round of Insecticide Treated Nets (ITN) mass campaign in 2019. Since 2013, over 2.4M ITN have been distributed through mass distribution. The proportion of those who slept under ITNs the night before the surveys of decreased from 55.9% in 2015 to 42.7% in 2021. Care seeking among children with fever in the state decreased from 65.8% in 2015 to 45.3% in 2021. Children with fever who had blood taken from a finger or heel for testing increased from 18.8% in 2015 to 24.0% in 2021. The coverage of intermittent preventive treatment of malaria in pregnancy who received two or more doses of SP decreased from 25.7% in 2015 to 19.9% in 2021.(ref_dhs_mis)</p>
<p>Cumulative estimated malaria cases averted was 840.7K in 2015 increased to 1.4M in 2021.</p>
<p>An estimated 840.7K cases were averted between 2009 and 2015, and1.4M between 2009 and 2021</p>
<table class="table">
<colgroup>
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"># Benue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"># Niger</td>
</tr>
<tr class="even">
<td style="text-align: left;">The state’s population was 6.2M as of the last census in 2019(ref_population_census), with an estimated population of 6.4M in 2022.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The state experiences two distinct seasons: the dry season (November - March) and the rainy season (April - October), with annual rainfall averaging around 1,101.7 millimeters.</td>
</tr>
<tr class="even">
<td style="text-align: left;">The state contributed an estimated 5.9% of Nigeria’s 65M malaria cases in 2021. Between 2018 and 2021, estimated cases increased from 3.7M to 4.1M, and the estimated incidence decreased from 368.9 to 351.5 per 1000 population(ref_wmr). Malaria prevalence by microscopy decreased from 33.5% in 2015 to 20.7% in 2021(ref_dhs_mis).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The state conducted its most recent round of Insecticide Treated Nets (ITN) mass campaign in 2019. Since 2013, over 2.6M ITN have been distributed through mass distribution. The proportion of those who slept under ITNs the night before the surveys of decreased from 38.0% in 2015 to 22.1% in 2021. Care seeking among children with fever in the state decreased from 81.9% in 2015 to 73.6% in 2021. Children with fever who had blood taken from a finger or heel for testing increased from 11.8% in 2015 to 22.1% in 2021. The coverage of intermittent preventive treatment of malaria in pregnancy who received two or more doses of SP increased from 13.2% in 2015 to 20.9% in 2021.(ref_dhs_mis)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cumulative estimated malaria cases averted was 1.6M in 2015 decreased to 581.9K in 2021.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">An estimated 1.6M cases were averted between 2009 and 2015, and581.9K between 2009 and 2021</td>
</tr>
</tbody>
</table>
</section>
<section id="kogi" class="level1">
<h1>Kogi</h1>
<p>The state’s population was 4.2M as of the last census in 2019(ref_population_census), with an estimated population of 5.3M in 2022.</p>
<p>The state experiences two distinct seasons: the dry season (November - March) and the rainy season (April - October), with annual rainfall averaging around 1,221.3 millimeters.</p>
<p>The state contributed an estimated 1.3% of Nigeria’s 65M malaria cases in 2021. Between 2018 and 2021, estimated cases decreased from 961.9K to 915.4K, and the estimated incidence decreased from 307.3 to 301.8 per 1000 population(ref_wmr). Malaria prevalence by microscopy was 15.9% in 2021(ref_dhs_mis).</p>
<p>The state conducted its most recent round of Insecticide Treated Nets (ITN) mass campaign in 2017. The proportion of those who slept under ITNs the night before the surveys of decreased from 22.3% in 2015 to 18.0% in 2021. Care seeking among children with fever in the state decreased from 93.4% in 2015 to 66.7% in 2021. Children with fever who had blood taken from a finger or heel for testing increased from 9.8% in 2015 to 21.1% in 2021. The coverage of intermittent preventive treatment of malaria in pregnancy who received two or more doses of SP decreased from 25.9% in 2015 to 23.7% in 2021.(ref_dhs_mis)</p>
<p>Cumulative estimated malaria cases averted was 3.4M in 2015 increased to 4.6M in 2021.</p>
<p>An estimated 3.4M cases were averted between 2009 and 2015, and4.6M between 2009 and 2021</p>
<table class="table">
<colgroup>
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"># Imo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"># Adamawa</td>
</tr>
<tr class="even">
<td style="text-align: left;">The state’s population was 4.5M as of the last census in 2019(ref_population_census), with an estimated population of 5.0M in 2022.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The state experiences two distinct seasons: the dry season (November - April) and the rainy season (May - October), with annual rainfall averaging around 1,074.9 millimeters.</td>
</tr>
<tr class="even">
<td style="text-align: left;">The state contributed an estimated 1.4% of Nigeria’s 65M malaria cases in 2021. Between 2018 and 2021, estimated cases increased from 923.2K to 961.3K, and the estimated incidence increased from 262.3 to 274.2 per 1000 population(ref_wmr). Malaria prevalence by microscopy decreased from 34.7% in 2015 to 10.7% in 2021(ref_dhs_mis).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The state conducted its most recent round of Insecticide Treated Nets (ITN) mass campaign in 2021. Since 2013, over 5.3M ITN have been distributed through mass distribution. The proportion of those who slept under ITNs the night before the surveys of increased from 31.6% in 2015 to 67.5% in 2021. Care seeking among children with fever in the state increased from 55.5% in 2015 to 65.6% in 2021. Children with fever who had blood taken from a finger or heel for testing increased from 10.2% in 2015 to 18.8% in 2021. The coverage of intermittent preventive treatment of malaria in pregnancy who received two or more doses of SP increased from 23.3% in 2015 to 24.7% in 2021.(ref_dhs_mis)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cumulative estimated malaria cases averted was -691.1K in 2015 decreased to -2.7M in 2021.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">No cases were estimated to be cumulatively averted between 2009 and 2015 as an increase in cases was observed during this period, no cases were estimated to be cumulatively averted between 2015 and 2021 as an increase in cases was observed during this period</td>
</tr>
</tbody>
</table>
</section>
<section id="jigawa" class="level1">
<h1>Jigawa</h1>
<p>The state’s population was 6.8M as of the last census in 2019(ref_population_census), with an estimated population of 6.9M in 2022.</p>
<p>The state experiences two distinct seasons: the dry season (November - March) and the rainy season (April - October), with annual rainfall averaging around 589.4 millimeters.</p>
<p>The state contributed an estimated 3.0% of Nigeria’s 65M malaria cases in 2021. Between 2018 and 2021, estimated cases decreased from 2.2M to 2.1M, and the estimated incidence decreased from 398.9 to 382.1 per 1000 population(ref_wmr). Malaria prevalence by microscopy decreased from 27.9% in 2015 to 25.4% in 2021(ref_dhs_mis).</p>
<p>The state conducted its most recent round of Insecticide Treated Nets (ITN) mass campaign in 2021. Since 2013, over 10.2M ITN have been distributed through mass distribution. The proportion of those who slept under ITNs the night before the surveys of decreased from 75.5% in 2015 to 63.4% in 2021. Care seeking among children with fever in the state decreased from 78.1% in 2015 to 76.3% in 2021. Children with fever who had blood taken from a finger or heel for testing increased from 11.1% in 2015 to 35.5% in 2021. The coverage of intermittent preventive treatment of malaria in pregnancy who received two or more doses of SP increased from 13.6% in 2015 to 17.7% in 2021.(ref_dhs_mis)</p>
<p>Cumulative estimated malaria cases averted was 924.9K in 2015 decreased to -1.7M in 2021.</p>
<p>An estimated 924.9K cases were averted between 2009 and 2015, no cases were estimated to be cumulatively averted between 2015 and 2021 as an increase in cases was observed during this period</p>
<table class="table">
<colgroup>
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"># Taraba</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"># Federal Capital Territory</td>
</tr>
<tr class="even">
<td style="text-align: left;">The state’s population was 2.7M as of the last census in 2019(ref_population_census), with an estimated population of 5.8M in 2022.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The state experiences two distinct seasons: the dry season (November - February) and the rainy season (March - October), with annual rainfall averaging around 1,215.0 millimeters.</td>
</tr>
<tr class="even">
<td style="text-align: left;">The state contributed an estimated 2.6% of Nigeria’s 65M malaria cases in 2021. Between 2018 and 2021, estimated cases increased from 1.3M to 1.9M, and the estimated incidence increased from 248.6 to 269.4 per 1000 population(ref_wmr). Malaria prevalence by microscopy decreased from 20.2% in 2015 to 18.8% in 2021(ref_dhs_mis).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The state conducted its most recent round of Insecticide Treated Nets (ITN) mass campaign in 2011. The proportion of those who slept under ITNs the night before the surveys of increased from 17.4% in 2015 to 28.6% in 2021. Care seeking among children with fever in the state decreased from 80.6% in 2015 to 77.7% in 2021. Children with fever who had blood taken from a finger or heel for testing increased from 18.0% in 2015 to 21.3% in 2021. The coverage of intermittent preventive treatment of malaria in pregnancy who received two or more doses of SP decreased from 20.0% in 2015 to 15.7% in 2021.(ref_dhs_mis)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cumulative estimated malaria cases averted was 348.8K in 2015 decreased to -3.3M in 2021.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">An estimated 348.8K cases were averted between 2009 and 2015, no cases were estimated to be cumulatively averted between 2015 and 2021 as an increase in cases was observed during this period</td>
</tr>
</tbody>
</table>
</section>
<section id="borno" class="level1">
<h1>Borno</h1>
<p>The state’s population was 5.8M as of the last census in 2019(ref_population_census), with an estimated population of 7.1M in 2022.</p>
<p>The state experiences two distinct seasons: the dry season (October - May) and the rainy season (June - September), with annual rainfall averaging around 660.0 millimeters.</p>
<p>The state contributed an estimated 1.9% of Nigeria’s 65M malaria cases in 2021. Between 2018 and 2021, estimated cases increased from 1.2M to 1.3M, and the estimated incidence increased from 260.7 to 288.5 per 1000 population(ref_wmr). Malaria prevalence by microscopy was 5.6% in 2021(ref_dhs_mis).</p>
<p>The state conducted its most recent round of Insecticide Treated Nets (ITN) mass campaign in 2011. The proportion of those who slept under ITNs the night before the surveys of decreased from 57.5% in 2015 to 34.2% in 2021. Care seeking among children with fever in the state was 48.1% in 2021. Children with fever who had blood taken from a finger or heel for testing was 13.6% in 2021. The coverage of intermittent preventive treatment of malaria in pregnancy who received two or more doses of SP NA from NA in 2015 to NA in 2021.(ref_dhs_mis)</p>
<p>Cumulative estimated malaria cases averted was 763.8K in 2015 decreased to -947.3K in 2021.</p>
<p>An estimated 763.8K cases were averted between 2009 and 2015, no cases were estimated to be cumulatively averted between 2015 and 2021 as an increase in cases was observed during this period</p>
<hr>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>